### ISSUE TITLE
Add active_route fields to Homey

### ISSUE THREAD

**Issue by robertraaijmakers** [RonnyWinkler/homey.tesla#2]
Hi there,

I just installed the Tesla app and it has a lot of features and triggers. However, the one I'm looking for is not yet in their and I think very useful to have as it unleashes a lot of power with regards to notifications.

So what I want to do is when I leave work (and locations depend, because working at different locations all the time) and enter in my navigation "Home", I want to sent a push notification to my wife with my ETA. However these details are not available, because I can't read the navigational data. It should be available somewhere, but I couldn't find the tesla API documentation.

If it helps, they implemented this a couple of months ago in the TeslaMate app: https://github.com/teslamate-org/teslamate/discussions/3018. So maybe you can find where they got the data from and add this as available data to Homey as well! :)

Just having the navigation data available, name, time & distance to destination available is enough!

Thanks!

**Comment by RonnyWinkler** [comment]
Added with version 1.10.0
